version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/Vancouver
    cooldown:
      default-days: 1
    groups:
      npm-minor-and-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/Vancouver
    groups:
      gradle-minor-and-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/Vancouver
    groups:
      actions-minor-and-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
